# Prompt for Project Field: Labels
# Use this prompt to ensure only valid values are used for the Labels field in GitHub Projects v2.

name: labels
values:
  - Use only labels that exist in the repository or organization.
  - If a label is missing, create it first or request its creation.

strict: true
usage: |
  Only use existing labels for the Labels field in Projects v2. If a value is not present, request an update to the prompt and the project configuration.
notes: |
  This prompt is designed to prevent API/CLI failures due to invalid label values. Use with gh copilot or models extensions for input validation.
