# Prompt for Project Field: Linked Pull Requests
# Use this prompt to ensure only valid values are used for the Linked Pull Requests field in GitHub Projects v2.

name: linked_pull_requests
values:
  - Use only pull requests that exist in the repository or organization.
  - If a pull request is missing, create it first or request its creation.

strict: true
usage: |
  Only use existing pull requests for the Linked Pull Requests field in Projects v2. If a value is not present, request an update to the prompt and the project configuration.
notes: |
  This prompt is designed to prevent API/CLI failures due to invalid pull request values. Use with gh copilot or models extensions for input validation.
