# Prompt for Project Field: Milestone
# Use this prompt to ensure only valid values are used for the Milestone field in GitHub Projects v2.

name: milestone
values:
  - Use only milestones that exist in the repository or organization.
  - If a milestone is missing, create it first or request its creation.

strict: true
usage: |
  Only use existing milestones for the Milestone field in Projects v2. If a value is not present, request an update to the prompt and the project configuration.
notes: |
  This prompt is designed to prevent API/CLI failures due to invalid milestone values. Use with gh copilot or models extensions for input validation.
