# Prompt for Project Field: Parent Issue
# Use this prompt to ensure only valid values are used for the Parent Issue field in GitHub Projects v2.

name: parent_issue
values:
  - Use only issues that exist in the repository or organization.
  - If a parent issue is missing, create it first or request its creation.

strict: true
usage: |
  Only use existing issues for the Parent Issue field in Projects v2. If a value is not present, request an update to the prompt and the project configuration.
notes: |
  This prompt is designed to prevent API/CLI failures due to invalid parent issue values. Use with gh copilot or models extensions for input validation.
