# Prompt for Project Field: Reviewers
# Use this prompt to ensure only valid values are used for the Reviewers field in GitHub Projects v2.

name: reviewers
values:
  - Use only users with access to the repository or organization.
  - If a reviewer is missing, add them to the org or repo first or request their addition.

strict: true
usage: |
  Only use existing users for the Reviewers field in Projects v2. If a value is not present, request an update to the prompt and the project configuration.
notes: |
  This prompt is designed to prevent API/CLI failures due to invalid reviewer values. Use with gh copilot or models extensions for input validation.
