# Prompt for Project Field: Size
# Use this prompt to ensure only valid values are used for the Size field in GitHub Projects v2.

name: size
values:
  - XS
  - S
  - M
  - L
  - XL

strict: true
usage: |
  Only use the above values for the Size field in Projects v2. If a value is not present, request an update to the prompt and the project configuration.
notes: |
  This prompt is designed to prevent API/CLI failures due to invalid size values. Use with gh copilot or models extensions for input validation.
