# Prompt for Project Field: Status
# Use this prompt to ensure only valid values are used for the Status field in GitHub Projects v2.

name: status
values:
  - Todo/New
  - Blocked
  - In Progress/Active
  - Testing/Review
  - Done/Closed
  # Add any additional org-approved status values here

strict: true
usage: |
  Only use the above values for the Status field in Projects v2. If a value is not present, request an update to the prompt and the project configuration.
notes: |
  This prompt is designed to prevent API/CLI failures due to invalid status values. Use with gh copilot or models extensions for input validation.
