# Prompt for Project Field: Sub-Issues Progress
# Use this prompt to ensure only valid values are used for the Sub-Issues Progress field in GitHub Projects v2.

name: sub_issues_progress
values:
  - Use only valid progress values as defined by the project configuration.

strict: true
usage: |
  Only use valid progress values for the Sub-Issues Progress field in Projects v2. If a value is not present, request an update to the prompt and the project configuration.
notes: |
  This prompt is designed to prevent API/CLI failures due to invalid sub-issues progress values. Use with gh copilot or models extensions for input validation.
