apiVersion: 2023-05-01
location: eastus
name: copilot-powerplatform-bot
properties:
  containers:
  - name: copilot-powerplatform-bot
    properties:
      image: ghcr.io/dynamicstms365/copilot-powerplatform/copilot-agent:latest
      ports:
      - port: 8080
        protocol: TCP
      - port: 8443
        protocol: TCP
      environmentVariables:
      - name: NGL_DEVOPS_APP_ID
        value: "1247205"
      - name: ASPNETCORE_ENVIRONMENT
        value: Production
      - name: ASPNETCORE_URLS
        value: "http://+:8080"
      - name: NGL_DEVOPS_PRIVATE_KEY
        secureValue: "$(GITHUB_APP_PRIVATE_KEY)"
      - name: NGL_DEVOPS_WEBHOOK_SECRET
        secureValue: "$(GITHUB_WEBHOOK_SECRET)"
      # Azure OpenAI Integration
      - name: AZURE_OPENAI_ENDPOINT
        value: "$(AZURE_OPENAI_ENDPOINT)"
      - name: AZURE_OPENAI_API_KEY
        secureValue: "$(AZURE_OPENAI_API_KEY)"
      - name: AZURE_OPENAI_DEPLOYMENT_NAME
        value: "gpt-4"
      - name: AZURE_OPENAI_API_VERSION
        value: "2024-02-15-preview"
      - name: AZURE_OPENAI_MAX_TOKENS
        value: "4096"
      - name: AZURE_OPENAI_TEMPERATURE
        value: "0.7"
      - name: AZURE_OPENAI_TIMEOUT
        value: "30"
      - name: AZURE_OPENAI_RETRY_COUNT
        value: "3"
      - name: AZURE_OPENAI_RATE_LIMIT_ENABLED
        value: "true"
      # Security Configuration
      - name: SECURITY_HEADERS_ENABLED
        value: "true"
      - name: CORS_ENABLED
        value: "true"
      - name: RATE_LIMITING_ENABLED
        value: "true"
      - name: HEALTH_CHECK_ENABLED
        value: "true"
      - name: METRICS_ENABLED
        value: "true"
      - name: LOGGING_LEVEL
        value: "Information"
      resources:
        requests:
          cpu: 1.0
          memoryInGb: 2.0
        limits:
          cpu: 2.0
          memoryInGb: 4.0
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: false
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
  identity:
    type: SystemAssigned
  imageRegistryCredentials:
  - server: ghcr.io
    username: cege7480
    password: "$(REGISTRY_PASSWORD)"
  ipAddress:
    type: Public
    ports:
    - protocol: tcp
      port: 8080
    - protocol: tcp
      port: 8443
    dnsNameLabel: copilot-powerplatform-$(date +%s | tail -c 6)
  osType: Linux
  restartPolicy: Always
  diagnostics:
    logAnalytics:
      workspaceId: "$(LOG_ANALYTICS_WORKSPACE_ID)"
      workspaceKey: "$(LOG_ANALYTICS_WORKSPACE_KEY)"
tags:
  environment: production
  project: copilot-powerplatform
  version: "${COPILOT_VERSION:-dev-local}"
  security: hardened
type: Microsoft.ContainerInstance/containerGroups
