name: Copilot PR Review Orchestration

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

jobs:
  demo_app_authentication:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Use the token
        env:
          GH_TOKEN: ${{ steps.generate-token.outputs.token }}
        run: |
          gh api octocat

  copilot_pr_orchestration:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up GitHub CLI
        uses: cli/gh-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Copilot CLI (if not present)
        run: |
          if ! gh extension list | grep -q gh-copilot; then
            gh extension install github/gh-copilot
          fi

      - name: Copilot CLI Suggestion for PR
        id: copilot_suggest
        run: |
          PR_TITLE="Demo Title"
          PR_BODY="Demo Body"
          PROMPT_FILE=".github/prompts/pr-review.txt"
          sed "s/\\$PR_TITLE/$PR_TITLE/g; s/\\$PR_BODY/$PR_BODY/g" $PROMPT_FILE > pr_prompt.txt
          gh copilot suggest "$(cat pr_prompt.txt)" > copilot_suggestion.txt

      - name: Output Copilot suggestion
        run: |
          cat copilot_suggestion.txt
