name: Simple Semantic Version Validation Test
on:
  workflow_dispatch:
  push:
    paths:
      - '.github/workflows/deploy-azure-container.yml'
      - '.github/workflows/components/semver-validation-test.yml'

jobs:
  test-basic-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Test Basic Semantic Version Validation
        run: |
          SEMANTIC_VERSION="1.2.3"
          echo "🧪 Testing version: '$SEMANTIC_VERSION'"
          
          # Validate semantic version format
          if [[ ! "$SEMANTIC_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "❌ VALIDATION: Invalid semantic version format: '$SEMANTIC_VERSION'"
            exit 1
          fi
          
          # Ensure version is not empty
          if [[ -z "$SEMANTIC_VERSION" ]]; then
            echo "❌ VALIDATION: Semantic version is empty"
            exit 1
          fi
          
          echo "✅ VALIDATION: Semantic version validation passed: $SEMANTIC_VERSION"

  test-invalid-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Test Invalid Semantic Version Detection
        run: |
          SEMANTIC_VERSION="1.2"
          echo "🧪 Testing invalid version: '$SEMANTIC_VERSION'"
          
          # Validate semantic version format - should fail
          if [[ ! "$SEMANTIC_VERSION" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "✅ CORRECTLY DETECTED: Invalid semantic version format: '$SEMANTIC_VERSION'"
            exit 0
          fi
          
          echo "❌ TEST FAILED: Should have detected invalid version"
          exit 1